name: favorite_products
description: Evaluation for the position of Software Engineer - Mobile - Flutter at Bemol Digital
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^0.1.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launch/launch_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - assets/svg/
    - assets/launch/
